PYTHON = python3
TEST_MODULE = unittest
RM = rm -rf
CACHE = __pycache__/

all: $(test)
	@echo "$$NMH_ASCII"
	$(PYTHON) -m $(TEST_MODULE) testutil/...

test:
	$(PYTHON) -m $(TEST_MODULE) testutil/...

test cafemenu:
	$(PYTHON) -m $(TEST_MODULE) testutil/testCafeMenu.py

test smoothie:
	$(PYTHON) -m $(TEST_MODULE) testutil/testSmoothie.py

clean: $(CACHE)
	$(RM) $(CACHE)

ascii:
	@echo "$$NMH_ASCII"


define NMH_ASCII

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0kdoolcccclodxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWWKkoc,........       ..cxXWWWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWMWW0o;.. ...........          ,d0XWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWXx;.     ........               .';ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNk,       ......                       'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMXl.        ..                             ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMW0;     ...                                  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMK:      .......';;;:;;,;;;,,'....             lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWx........;codxkO0000OOOOOkkkxdoc;,........    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNo.....':d0KXXXXXXKKKKK000000OOkxdlc;'.''....   ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXc..'',cx0KXXXXXXXKKKKK000000OOOkxdolc;,,,'.    .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWl....':d0KXXXXXXXKKKKK000000OOOkxddolc;;;,.    .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWx....,:d0XXXXXXXXKK0KK00KKK0Okkdolllol;,'.     .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMk'...,:d0K0OkkkOkk000K00K0koccc;,,,,:c::,.     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMW0;..',cOK0kkkkOOOO000X0kOOkkkkkkkdl:::cc;.     :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWWNo...;dKK0KK00OkOO00KX0xdk0K0OOxlcclcclc:,.  ..,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMW0l,',xXKK0kxd::ldk0XXKxlokkxkko;:ccclllc:'..',,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWKOkllOXXXK0K0xxkk0KXXXOdllxO000OOkxdddolc:,..,c0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWXKKK0KKXXXKKKKKKKKXXXX0xlclxkO0KK00Okxolc:;..,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWXKOk0XXXXXKK00KKKXXKX0xocldxk0KKKKOkxdlcc:,,oXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWN0OKXXXXXKK00O0KKKXXKkollllokK000Oxdlc:::::kWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWNXKKKXXXKKOkx0KKKXK0kdool:,;x00Okdlc:::::l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKKK0xdOKK00K0kdl:ccc:;lkOxdoc::c::lOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWNXKXKK0kxOXXXXXKK00kxdoollooxkkdlccc:;dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKKK0kOKK0000OOOkdolcc:;;lxOOocc::;,'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKKK00KK0Okkkxdlcc:;;,;cdOOo:::;,,;. ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXXKKK00kxdoc::cldxxl;::,,';c'  .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKXXKKK0Okxxdoooodddc;,;,'',l:.    ;ONWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX00KXXXXXK000Okxxxol:;'''.':oc.      .:x0XWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOxO0KKKKK000Okxolc;,''..',lo:.          .';okXWMMWMMMWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWWMMMMWX0kol;'.cKX0000OOkxxollcc;,,,,:ldo,                .':dOXWMWWWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNXOxl;'.  ....cXNKKK00Okxxddooolodxkkxo,                ..   ..:okKWMMMMMMMMMMM
MMMMMMMMMMMMMMMMWXOdc;..     ......lXWNXXXKK0OOkOO00XNNX0Od,             ...........  ..:oONMMMMMMMM
MMMMMMMMMMMWWKkl:'.        ......'.lXWWNKKKKKKKXNWWWWWNX0d;.            ................  .,cxKWMMMM
MMMMMMMMN0dl:.           ........'.lXWWWNKKXXNWWWWWWNNXKx;..       .    ...................  ..:dKNM
MMMMMMWKc.              ........''.oNNNK0OOKNWWWWWWWNXKx;.....   .....  .......................  .;o
MMMMMM0,     ..  ... ...........'',kKkkkkO00KXWWWNWNNXk;....... .................................   
MMMWMX:. .......................'.:Oxoxk0K0OkdxKNNNNXk;.........................................    
MMMMNo............................lkOkx0K0xlclclOXNNO;..............'''..'........''...........     
MMMMk'.........................'..lONKk00dcllclkKNN0:.'................''........'''.........       
MMMXc... .........................kNNK0Ooccc:d0NW0d:'''..'..............'.'''''.''''........        
MMMO,... ........................;0WX00kccc:oKNWKc,''''.'...............'''''''''...........        
MMNo.... .....................'..;ONKO0xcclcxXWXl''''..''...............''''''.............         
MM0;..'. .....................'..,dOxk0occcldKXo'''''..'''.............'''''''............          
MWx..... .....................'..'looO0o:clodko,''.'''''''..........'''''''''............           
MXc..... ....................'...,lld00dcclodc,'''..'''''''.......''''''''''......  ....            
M0,..........................'.  ;ookKKxlcloc,''''..'''''..''...'''''''''''.....    ...             
Wk'..........................'. .cddOXKOoooc,'''''..'''''.'....'''''''........     ...              
Xc..........................''. .oxk0XX0kxl,''''''''''''''....''''''..........    ...               
k'....'.....................''. 'dk0KXXK0x;''''''''''''''...''''''...........     ....              
c...........................,'. ,xOKXXXKOc','''''''''''....'''''.............    .....              
'..........................',.  ;k0KXXXKo,,,''''''''''...''''''.............    ..'...              
.....................'''...',.  :OKXXXXd;','''''''''...',''''....... ......     ..'...              


endef
export NMH_ASCII
